Parameters:
  FullRepoName:
    Type: String
    Default: rkamphorst/lambdacg

Resources:

  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GithubLambdaCgTestingRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Policies:
        - PolicyName: CreateInvokeAndDeleteLambdaCgTestLambdas
          PolicyDocument:
            Version: 2012-10-17
            Statement: 
              - Sid: PermissionToCreateFunction
                Effect: Allow
                Action: 
                  - lambda:CreateFunction
                  - lambda:GetFunction
                  - lambda:DeleteFunction
                  - lambda:UpdateFunctionCode
                  - lambda:InvokeFunction
                  - lambda:GetFunctionConfiguration
                Resource: 
                  - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:lambdacg-* 
              - Sid: PermissionToPassARole
                Effect: Allow
                Action: iam:PassRole
                Resource: 
                  - !GetAtt LambdaExecutionRole.Arn
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GithubOidc
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${FullRepoName}:*

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaCgLambdaExecutionRole
      Policies:
        - PolicyName: DenyLoggingAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement: 
              - Sid: DisableAllLogs
                Action: 
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Deny
                Resource: '*'

      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
        

  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - !Sub https://github.com/${FullRepoName}
        - sts.amazonaws.com
        - sigstore
      ThumbprintList:
        - a031c46782e6e6c662c2c87c76da9aa62ccabd8e
        - 6938FD4D98BAB03FAADB97B34396831E3780AEA1

Outputs:
  Role:
    Value: !GetAtt Role.Arn
