Parameters:
  FullRepoName:
    Type: String
    Default: rkamphorst/lambdacg

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GithubLambdaCgTestingRole
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GithubOidc
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${FullRepoName}:*

  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList: 
        - !Sub https://github.com/${FullRepoName}
        - sts.amazonaws.com
        - sigstore
      ThumbprintList:
        - a031c46782e6e6c662c2c87c76da9aa62ccabd8e

Outputs:
  Role:
    Value: !GetAtt Role.Arn  