name: Lint and Test

on:
  - pull_request

jobs:
  lintAndTest:

    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        node-version: [16.x, 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        # The code in this repo must run on AWS lambda. At the time of writing, node 16 is LTS, 
        # but lambda doesn't support it (yet).
        # See https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html.
        # We therefore want to support 14 *and* 16.

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn set version berry
    - run: yarn install --immutable
    - run: yarn run lint
    - run: yarn test
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: ${{ secrets.AWS_TESTING_ROLE }}
        aws-region: eu-west-1
    - run: npm run component-test

