name: Test Coverage

on:
  - push

jobs:
  testCoverage:

    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Upgrade NPM
      run: npm install -g npm
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: ${{ secrets.AWS_TESTING_ROLE }}
        aws-region: eu-west-1
    - run: npm ci
    - run: npm run test-coverage
